// NBA Teams
const teams = [
    'Boston Celtics',
    'Brooklyn Nets',
    'New York Knicks',
    'Philadelphia 76ers',
    'Toronto Raptors',
    'Chicago Bulls',
    'Cleveland Caveliers',
    'Detroit Pistons',
    'Indiana Pacers',
    'Milwaukee Bucks',
    'Atlanta Hawks',
    'Charlotte Hornets',
    'Miami Heat',
    'Orlando Magic',
    'Washington Wizards',
    'Denver Nuggets',
    'Minnesota Timberwolves',
    'Oklahoma City Thunder',
    'Portland Trail Blazers',
    'Utah Jazz',
    'Golden State Warriors',
    'Los Angeles Clippers',
    'Los Angeles Lakers',
    'Phoenix Suns',
    'Sacramento Kings',
    'Dallas Mavericks',
    'Houston Rockets',
    'Memphis Grizzlies',
    'New Orleans Pelicans',
    'San Antonio Spurs',
];

export default teams;